extends:
  - standard
  - prettier
  - prettier/standard
plugins:
  - mocha
env:
  mocha: true
# テスト用のグローバル変数 # TODO: 自動的にglobalを認識させたい
globals:
  assert: true
  doukaku: true
rules:
  no-debugger: off
  no-var: error
  prefer-const: error
